spring.application.name=seats-allocation-service
api.prefix=/seats-allocation-service/v1
server.servlet.context-path=${api.prefix}

# PostgreSQL datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/allocation_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

# Spring profiles
spring.profiles.group.dev=dev,common
spring.profiles.group.qa=qa,common
spring.profiles.group.prod=prod,common

app.kafka.topics.inventory-init-request=${APP_KAFKA_TOPIC_INVENTORY_INIT_REQUEST:inventory-init.v1}
app.kafka.topics.inventory-init-result=${APP_KAFKA_TOPIC_INVENTORY_INIT_RESULT:inventory-published.v1}
app.inventory.default-currency=${APP_INVENTORY_DEFAULT_CURRENCY:USD}
